### ISSUE TITLE
problem with multicoloured buoys in preset

### ISSUE THREAD

**Issue by Skippern** [OpenSeaMap/josm#13]
I noticed that the way the preset is set now, I have problems selecting multicoloured buoys with repeating colours (red;green;red, green;white;green;white, etc.) This applies to **Seamarks/Q: Buoys, Beacons/Buoys and Floats (Q20-Q71)/Buoys in General/Lateral Buoy** which you get a short-cut to from the top of tag window when selecting an already tagged lateral buoy. With the current status we risk that people inadvertently mess up colouring of buoys when trying to fix other faults (luckily I suspected this, and fixed the colours manually)

**Comment by malcolmh** [comment]
There is an inherent problem with presets when ordered multi-values are needed. There is no way round this. It might be better to remove the whole Buoys-in-General group.

**Comment by Skippern** [comment]
@malcolmh as you saw in [this changeset](http://www.openstreetmap.org/changeset/29414275) with [this node](http://www.openstreetmap.org/node/2118496641/history), corrected in [this changeset](http://www.openstreetmap.org/changeset/29424569) - Version 3 of the node was missing **seamark:buoy_lateral:colour_pattern**, when trying to correct this (with the short-cut), I noticed colour **green;red;green** being stripped to **red;green** and fixed that manually. It didn't occur to me that it might actually alter the category as well

I think we can keep the *general buoy* in the preset, but change all keys to **match=none** so it doesn't come up as short cut in the tagging window.

**Comment by Skippern** [comment]
I havn't had any more issues with this, can we close this issue @malcolmh ?

**Comment by malcolmh** [comment]
I made some changes to mitigate this problem, so we will close it for now.
