### ISSUE TITLE
INT1_MapCSS.mapcss: feedback

### ISSUE THREAD

**Issue by Dirk--** [OpenSeaMap/josm#14]
Thanks Aun, nice work!

To suit my needs, I would suggest to focus just on 'seamark' tags. This way, your preset would reflect only objects rendered on OSeaM's seamark layer.

Some years ago, I have set up a CEVNI notemark style. Works well on top of yours. I should do a review and add it to this repository...

**Comment by Skippern** [comment]
@Dirk-- It started out as a full INT-1 style, but focus is now only on `seamark` tags, I have not taken any actions removing non-seamark tags, but I might start reducing the number of non-seamark tags in the set.

If there are any specific things missing, or if you find any errors (misplaced objects, wrong symbol, etc.), make an issue, so I can work on it when I have time

**Comment by Skippern** [comment]
As specific CEVNI style have been added, and this issue seems mainly as a feedback, I close it now
