### ISSUE TITLE
INT1_MapCSS.mapcss: missing icons

### ISSUE THREAD

**Issue by Dirk--** [OpenSeaMap/josm#19]
Hi Aun,

I get lots of white placeholders where beacons and buoys should show up. Status report says:

 Last errors/warnings:
 - E: Failed to locate image 'https://raw.githubusercontent.com/OpenSeaMap/josm/master/icons/svg/Q//.svg'
 - E: Failed to locate image 'https://raw.githubusercontent.com/OpenSeaMap/josm/master/icons/svg/Q//.svg'
 - E: Failed to locate image 'https://raw.githubusercontent.com/OpenSeaMap/josm/master/icons/svg/Q//.svg'
 - E: Failed to locate image 'https://raw.githubusercontent.com/OpenSeaMap/josm/master/icons/svg/Q//.svg'
 - E: Failed to locate image 'https://raw.githubusercontent.com/OpenSeaMap/josm/master/icons/svg/Q//.svg'

I am testing in this area: https://www.openstreetmap.org/#map=13/52.5844/5.8419

**Comment by Skippern** [comment]
I think you have some objects on the map that is not correctly mapped

By the missing icons it have `seamark:type=*_buoy` or `*_beacon` tagged

But it seems you are missing `seamark:*_buoy:shape` and `seamark:*_buoy:colour`

I will need the day to look into what is going on here. I notice that they should be identified as 'https://raw.githubusercontent.com/OpenSeaMap/josm/master/icons/svg/Q/{shape}/{colour_pattern}/{colour}.svg'

See https://www.openstreetmap.org/node/1333850934 from your example area

**Comment by Skippern** [comment]
From line 503:

```
icon-image:		eval(concat("https://raw.githubusercontent.com/OpenSeaMap/josm/master/icons/svg/Q/", 
                coalesce(tag(concat("seamark:",tag("seamark:type"),":shape")), "buoyant"), "/", 
                cond(has_tag_key(concat("seamark:",tag("seamark:type"),":colour_pattern")),
                concat(tag(concat("seamark:",tag("seamark:type"),":colour_pattern")),"/"), ""), 
                coalesce(replace(tag(concat("seamark:",tag("seamark:type"),":colour")),";","_"), 
                "generic"), ".svg" ));
```

The node I linked in previous node should have been recognised as:
'https://raw.githubusercontent.com/OpenSeaMap/josm/master/icons/svg/Q/can/horizontal/red_white_red_white.svg'
This file exists in the repo

I will check another area, but I think it is a problem in JOSM MapCSS, either syntax change or recent changes to MapCSS have broken something

**Comment by Skippern** [comment]
I just checked https://www.openstreetmap.org/#map=13/-22.8559/-43.153 and the same problem. This was my reference area when adjusting icon offsets in March. I think this have been broken in later update of JOSM and opened a ticket there [JOSM#11436](https://josm.openstreetmap.de/ticket/11436) - until I have feedback from JOSM team I will treat this as a JOSM issue.
