### ISSUE TITLE
SMED IALA-B hidden

### ISSUE THREAD

**Issue by Nautic** [OpenSeaMap/josm#20]
The interface shows IALA-A-system, without indicating that it is IALA-A.
IALA-B is hidden behind the "<<"

IALA-A/B should be on the top of the table.
IALA-B should change the colour of lateral starbord and port.

**Comment by malcolmh** [comment]
SMED is not in this repository. It is in http://svn.openstreetmap.org/applications/editors/josm/plugins/smed/. Also no more development is  being done on that project.
