### ISSUE TITLE
Adding files from this repo to JOSM wiki lists

### ISSUE THREAD

**Issue by Skippern** [OpenSeaMap/josm#21]
@malcolmh Several files in this repo, such as all paint style mapcss and the validator.mapcss files should be added to the respective lists on [JOSM](http://josm.openstreetmap.de/), don't you think?

Also JOSM have added a column for icon on the tables on the wiki, maybe these files, and the preset should be identified with the OpenSeaMark icon as well?

**Comment by malcolmh** [comment]
Let me know which styles are ready for publication & I will add them to the JOSM wiki.

I have added the icon to the preset.

**Comment by Dirk--** [comment]
no need to add CEVNI_MapCSS.mapcss yet: https://github.com/OpenSeaMap/josm/commit/fc8ab68053a2baa3bc64f5a5e03890a3371d972f for details ...

**Comment by Skippern** [comment]
INT1 and validator should be ready for publish, we should probably sort out the discussion open in my previous commit before publishing PPWBC and BNIWR, though from my part they should be ready.

**Comment by malcolmh** [comment]
Done
